
USE RediDropper;

DELETE FROM Version where verID = '002';

DROP VIEW  IF EXISTS subject_file_view;
DROP VIEW  IF EXISTS user_role_view;

DROP TABLE IF EXISTS Log;
DROP TABLE IF EXISTS LogType;
DROP TABLE IF EXISTS WebSession;
DROP TABLE IF EXISTS UserAgent;

DROP TABLE IF EXISTS SubjectFile;
DROP TABLE IF EXISTS Event;
DROP TABLE IF EXISTS Subject;

DROP TABLE IF EXISTS UserRole;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS User;
