# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #config.vm.box = "puphpet/debian75-x64"
  config.vm.box = "debian/jessie64"
  config.vm.hostname = "redi-dropper-client"
  config.vm.synced_folder "../app", "/var/www/dropper/app"
  config.vm.network "forwarded_port", guest: 80, host: 8088
  config.vm.network :forwarded_port, guest: 443, host: 7088
  config.vm.network :forwarded_port, guest: 9392, host: 9392

  config.vm.provision "shell" do |s|
    s.path = "bootstrap.sh"
  end

  # Restart apache when all done (if using apache)
  config.vm.provision "shell", run: "always", inline: "service apache2 restart"

  if Vagrant.has_plugin?('vagrant-triggers')
    config.trigger.after [:up] do
      if Vagrant::Util::Platform.darwin?
        system("open -a 'Google Chrome.app' https://localhost:7088")
      end
    end
  end
end
