#!/bin/bash

# Helper script for starting the embedded webserver in the vagrant

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

. /var/www/app/venv/bin/activate

python /var/www/app/run.py --port 443 &
