# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # config.vm.box = "puphpet/debian75-x64"
  config.vm.box = "debian-jessie"
  config.vm.hostname = "redi-dropper-client"
  config.vm.synced_folder "../app", "/var/www/app"

  # http://docs.vagrantup.com/v2/networking/private_network.html
  config.vm.network "private_network", ip: "192.168.50.100"

  config.vm.network "forwarded_port", guest: 80, host: 8088
  config.vm.network "forwarded_port", guest: 443, host: 7443
  config.vm.network "forwarded_port", guest: 5000, host: 5002

  config.vm.provision "shell" do |s|
    s.path = "bootstrap.sh"
  end
end
